#### Introduction to Numpy

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(np.__version__)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
2.1.3


#### Creating 0D, 1D, 2D and 3D Numpy Arrays

In [10]:
arr0 = np.array(42)
arr1 = np.array([1,2,3])
arr2 = np.array([[1,5,2],[1,3,4]])
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr0)
print(arr1)
print(arr2)
print(arr3)

42
[1 2 3]
[[1 5 2]
 [1 3 4]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
