In [1]:
import numpy as np

# NumPy Array Copy and View


The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.



### copy of array

In [3]:
arr = np.array([1,2,3,5])
arr2 = arr.copy()
print(arr,arr2)

[1 2 3 5] [1 2 3 5]


### View of an array

In [4]:
arr = np.array([1,2,3,4,5])
arr_view = arr.view()
print(arr,arr_view)

[1 2 3 4 5] [1 2 3 4 5]


### Making changes in the copy

In [15]:
arr = np.array([1,2,3,5])
arr_copy = arr.copy()
arr_copy=np.append(arr_copy,12)
print(arr_copy) 
print(arr)

[ 1  2  3  5 12]
[1 2 3 5]


### Making changes in the view

In [17]:
org_arr=np.array([1,2,3,4,5])
view_arr = org_arr.view()
view_arr[3] =0
print(view_arr)
print(org_arr)


[1 2 3 0 5]
[1 2 3 0 5]


#### Every NumPy array has the attribute "base" that returns None if the array owns the data.

In [20]:
print(org_arr.base)   # own the data
print(view_arr.base) # does not own the data
print(arr_copy.base) # own the data

None
[1 2 3 0 5]
None
