In [1]:
import numpy as np

# NumPy Array Shape


In [2]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)


(2, 3)


### Reshape From 1-D to 2-D


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(4,3)
print(arr)
print(new_arr)
print(new_arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


### Returns Copy or View?


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(4,2).base)  ## returns the view of original array

[1 2 3 4 5 6 7 8]


### Flattening the arrays


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]
