In [1]:
import numpy as np

# NumPy Joining Array


In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


#### Join two 2-D arrays along rows (axis=1):



In [11]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
new_arr = np.concatenate((arr1,arr2),axis=1)
print(new_arr)


[[1 2 5 6]
 [3 4 7 8]]


### Joining Arrays Using Stack Functions


In [17]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
new_arr = np.stack((arr1,arr2),axis=1)
print(new_arr)


[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [18]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
new_arr = np.hstack((arr1,arr2))
print(new_arr)


[[1 2 5 6]
 [3 4 7 8]]


In [19]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
new_arr = np.vstack((arr1,arr2))
print(new_arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
new_arr = np.dstack((arr1,arr2))
print(new_arr)


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
